const whiteTextStyle = {
	fill: '#fff',
	shadowOffsetX: 0,
	shadowOffsetY: 2,
	shadowColor: '#0061D1',
	shadowBlur: 2,
};

export const dataSource = {
	nodes: [
		{
			id: 'water',
			x: 90,
			y: 153.5,
			size: [307, 251],
			img: require('@/assets/diagram/pic_water@2x.png'),
			type: 'image',
			label: '水源地',
			labelCfg: {
				position: 'bottom',
			},
			anchorPoints: [
				[0.92, 0.68],
				[1, 0.5],
			],
		},
		{
			id: 'pump',
			x: 384,
			y: 159,
			size: [90, 80],
			img: require('@/assets/diagram/pic_pump@2x.png'),
			type: 'image',
			label: '水泵',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.4, 0.43],
				[0.8, 0.43],
			],
		},
		{
			id: 'waterworks',
			x: 537.5,
			y: 95,
			size: [189, 124],
			img: require('@/assets/diagram/pic_waterworks@2x.png'),
			type: 'image',
			label: '           水厂',
			labelCfg: {
				position: 'top',
				offset: -3,
			},
			anchorPoints: [
				[0.4, 0.87],
				[0.6, 0.95],
				[0.83, 0.75],
			],
		},
		{
			id: 'metering1',
			x: 712,
			y: 66,
			size: [34, 64],
			img: require('@/assets/diagram/pic_metering@2x.png'),
			type: 'image',
			label: '测压点',
			labelCfg: {
				position: 'right',
			},
			anchorPoints: [
				[0.1, 0.7],
				[0.8, 0.7],
			],
		},
		{
			id: 'point7',
			x: 760,
			y: 50,
			size: [8, 8],
			type: 'rect-animate',
			label: '0.43 Mpa',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'site1',
			x: 850.5,
			y: 84.5,
			size: [73, 111],
			img: require('@/assets/diagram/pic_site@2x.png'),
			type: 'image',
			label: '加压泵站',
			labelCfg: {
				position: 'top',
				offset: 5,
			},
			anchorPoints: [
				[0.05, 0.458],
				[0.95, 0.458],
			],
		},
		{
			id: 'large_meter',
			x: 1003.5,
			y: 76.5,
			size: [63, 71],
			img: require('@/assets/diagram/pic_large_meter@2x.png'),
			type: 'image',
			label: '大水表',
			labelCfg: {
				position: 'bottom',
			},
			anchorPoints: [
				[0.05, 0.56],
				[0.95, 0.56],
			],
		},
		{
			id: 'factory',
			x: 1157.5,
			y: 87,
			size: [167, 126],
			img: require('@/assets/diagram/pic_factory@2x.png'),
			type: 'image',
			label: '               工厂',
			labelCfg: {
				position: 'top',
				offset: -5,
			},
			anchorPoints: [
				[0, 0.45],
				[0.8, 0.46],
			],
		},
		{
			id: 'metering2',
			x: 712,
			y: 188,
			size: [34, 64],
			img: require('@/assets/diagram/pic_metering@2x.png'),
			type: 'image',
			label: '测压点',
			labelCfg: {
				position: 'right',
			},
			anchorPoints: [
				[0.1, 0.7],
				[0.8, 0.7],
			],
		},
		{
			id: 'point6',
			x: 760,
			y: 170,
			size: [8, 8],
			type: 'rect-animate',
			label: '0.86 Mpa',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'site2',
			x: 850.5,
			y: 198.5,
			size: [73, 111],
			img: require('@/assets/diagram/pic_site@2x.png'),
			type: 'image',
			label: '加压泵站',
			labelCfg: {
				position: 'bottom',
			},
			anchorPoints: [
				[0.05, 0.535],
				[0.95, 0.535],
			],
		},
		{
			id: 'meter',
			x: 972,
			y: 170,
			size: [46, 52],
			img: require('@/assets/diagram/pic_meter@2x.png'),
			type: 'image',
			label: '水表',
			labelCfg: {
				position: 'bottom',
			},
			anchorPoints: [
				[0.05, 0.5],
				[0.95, 0.5],
			],
		},
		{
			id: 'pool',
			x: 1014.5,
			y: 244.5,
			size: [113, 75],
			img: require('@/assets/diagram/pic_pool@2x.png'),
			type: 'image',
			label: '水箱',
			labelCfg: {
				position: 'left',
				offset: 2,
			},
			anchorPoints: [
				[0.5, 0.1],
				[0.7, 0.7],
			],
		},
		{
			id: 'water_pump',
			x: 1151,
			y: 244.5,
			size: [84, 92],
			img: require('@/assets/diagram/pic_water_pump@2x.png'),
			type: 'image',
			label: '             二供设备',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.15, 0.665],
				[0.38, 0],
				[0.38, 0.9],
				[1, 0.665],
			],
		},
		{
			id: 'building',
			x: 1278.5,
			y: 250,
			size: [111, 200],
			img: require('@/assets/diagram/pic_building@2x.png'),
			type: 'image',
			label: '                             居民楼',
			labelCfg: {
				position: 'bottom',
				offset: -20,
			},
			anchorPoints: [
				[0, 0.55],
				[0.45, 0.1],
				[1, 0.5],
			],
		},
		{
			id: 'point9',
			x: 1330,
			y: 150,
			size: [8, 8],
			type: 'rect',
			label: '储水箱',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'sewage',
			x: 1528,
			y: 80,
			size: [175, 103.2],
			img: require('@/assets/diagram/pic_building.png'),
			type: 'image',
			label: '污水厂',
			labelCfg: {
				position: 'top',
			},
			anchorPoints: [
				[0.4, 0.85],
				[0.7, 0.85],
			],
		},
		{
			id: 'river',
			x: 1536,
			y: 220,
			size: [127, 88.4],
			img: require('@/assets/diagram/pic_water.png'),
			type: 'image',
			label: '江河湖海',
			labelCfg: {
				position: 'bottom',
			},
			anchorPoints: [[0.72, 0.2]],
		},
		{
			id: 'city',
			x: 1750,
			y: 184,
			size: [191, 256],
			img: require('@/assets/diagram/pic_city@2x.png'),
			type: 'image',
			label: '                                   水司',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.3, 0.95],
				[0.45, 0.95],
			],
		},
		{
			id: 'point5',
			x: 1800,
			y: 80,
			size: [8, 8],
			type: 'rect',
			label: '产销差分析',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'system',
			x: 220,
			y: 340,
			size: [85, 102],
			img: require('@/assets/diagram/pic_system@2x.png'),
			type: 'image',
			label: '                         源水管理',
			labelCfg: {
				position: 'bottom',
				offset: -3,
			},
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
		},
		{
			id: 'point1',
			x: 220,
			y: 410,
			size: [8, 8],
			type: 'rect',
			label: ' ',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'point2',
			x: 1380,
			y: 171.5,
			size: [8, 8],
			type: 'rect',
			label: ' ',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'file',
			x: 364,
			y: 336.5,
			size: [84, 109],
			img: require('@/assets/diagram/pic_file@2x.png'),
			type: 'image',
			label: '                         制水管理',
			labelCfg: {
				position: 'bottom',
				offset: -3,
			},
			anchorPoints: [
				[0.5, 0.08],
				[0.5, 1],
			],
		},
		{
			id: 'point3',
			x: 364,
			y: 410,
			size: [8, 8],
			type: 'rect',
			label: ' ',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'administration',
			x: 511,
			y: 345,
			size: [84, 93],
			img: require('@/assets/diagram/pic_administration@2x.png'),
			type: 'image',
			label: '                         供水管理',
			labelCfg: {
				position: 'bottom',
				offset: -3,
			},
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
				[1, 0.6],
			],
		},
		{
			id: 'point4',
			x: 511,
			y: 410,
			size: [8, 8],
			type: 'rect',
			label: ' ',
			style: {
				lineWidth: 0,
			},
			anchorPoints: [[0.5, 0.5]],
		},
		{
			id: 'service',
			x: 650,
			y: 345,
			size: [81, 96],
			img: require('@/assets/diagram/pic_service@2x.png'),
			type: 'image',
			label: '                         营销客服',
			labelCfg: {
				position: 'bottom',
				offset: -3,
			},
			anchorPoints: [
				[0, 0.6],
				[0.5, 1],
				[1, 0.6],
			],
		},
		{
			id: 'date_factory',
			x: 600,
			y: 513.5,
			size: [220, 183],
			img: require('@/assets/diagram/pic_date_factory@2x.png'),
			type: 'image',
			label: '                                  数据工厂',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.03, 0.58],
				[0.96, 0.6],
			],
		},
		{
			id: 'date_maintain',
			x: 880,
			y: 513.5,
			size: [239, 163],
			img: require('@/assets/diagram/pic_date_maintain@2x.png'),
			type: 'image',
			label: '                                  数据运维',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.03, 0.61],
				[0.85, 0.61],
			],
		},
		{
			id: 'date_quality',
			x: 1160.5,
			y: 530,
			size: [220, 156],
			img: require('@/assets/diagram/pic_dashbord_data@2x.png'),
			type: 'image',
			label: '                                  数据质量',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.03, 0.5],
				[0.98, 0.5],
			],
		},
		{
			id: 'date_assets',
			x: 1440.5,
			y: 513.5,
			size: [189, 176],
			img: require('@/assets/diagram/pic_date_assets@2x.png'),
			type: 'image',
			label: '                                  数据资产',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.03, 0.6],
				[0.98, 0.6],
			],
		},
		{
			id: 'date_service',
			x: 1700,
			y: 527.5,
			size: [192, 135],
			img: require('@/assets/diagram/pic_date_service@2x.png'),
			type: 'image',
			label: '                                  数据服务',
			labelCfg: {
				position: 'bottom',
				offset: -5,
			},
			anchorPoints: [
				[0.03, 0.52],
				[0.715, 0.1],
			],
		},
		{
			id: 'table_header',
			x: 220,
			y: 453,
			size: [463, 70],
			img: require('@/assets/diagram/pic_huge_pool@2x.png'),
			type: 'image',
			label: '供水生态',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
			anchorPoints: [
				[0.5, 0.1],
				[0.506, 0.78],
			],
		},
		{
			id: 'table_body1',
			x: 53.5,
			y: 512,
			size: [127, 58],
			img: require('@/assets/diagram/pic_secondary_pool@2x.png'),
			type: 'image',
			label: '源水',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
			anchorPoints: [
				[0.5, 0.2],
				[0.5, 0.7],
			],
		},
		{
			id: 'table_body2',
			x: 164.5,
			y: 512,
			size: [127, 58],
			img: require('@/assets/diagram/pic_secondary_pool@2x.png'),
			type: 'image',
			label: '净水',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
			anchorPoints: [
				[0.5, 0.2],
				[0.5, 0.7],
			],
		},
		{
			id: 'table_body3',
			x: 278.5,
			y: 512,
			size: [127, 58],
			img: require('@/assets/diagram/pic_secondary_pool@2x.png'),
			type: 'image',
			label: '供水',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
			anchorPoints: [
				[0.5, 0.2],
				[0.5, 0.7],
			],
		},
		{
			id: 'table_body4',
			x: 390.5,
			y: 512,
			size: [127, 58],
			img: require('@/assets/diagram/pic_secondary_pool@2x.png'),
			type: 'image',
			label: '售水',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
			anchorPoints: [
				[0.5, 0.2],
				[0.5, 0.7],
				[0.9, 0.76],
			],
		},
		{
			id: 'table_footer1',
			x: 27,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '源水\n生产',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer2',
			x: 83,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '源水\n检测',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer3',
			x: 137,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '制水\n生产',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer4',
			x: 193,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '制水\n检测',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer5',
			x: 250,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '管网',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer6',
			x: 306,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '二供',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer7',
			x: 364,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '报装\n营收',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
		{
			id: 'table_footer8',
			x: 420,
			y: 613,
			size: [108, 128],
			img: require('@/assets/diagram/pic_small_pool@2x.png'),
			type: 'image',
			label: '抄表\n客服',
			labelCfg: {
				position: 'center',
				style: whiteTextStyle,
			},
		},
	],
	edges: [
		{
			source: 'water',
			target: 'pump',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'pump',
			target: 'waterworks',
			type: 'path-across-oneturn-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'metering1',
			type: 'path-across-twoturn-blue',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'metering2',
			type: 'path-across-twoturn-blue',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'metering1',
			target: 'site1',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'site1',
			target: 'large_meter',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'large_meter',
			target: 'factory',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'factory',
			target: 'point2',
			type: 'path-across-oneturn-grey',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'point2',
			target: 'sewage',
			type: 'path-across-oneturn-grey',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'point2',
			target: 'sewage',
			type: 'path-across-oneturn-animate',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'sewage',
			target: 'river',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'sewage',
			target: 'river',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'metering2',
			target: 'site2',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'site2',
			target: 'meter',
			type: 'path-across-twoturn-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'meter',
			target: 'pool',
			type: 'path-across-oneturn-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'pool',
			target: 'water_pump',
			type: 'path-blue',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'building',
			type: 'path-blue',
			sourceAnchor: 3,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'building',
			type: 'path-vertical-oneturn-blue',
			sourceAnchor: 1,
			targetAnchor: 1,
		},
		{
			source: 'building',
			target: 'point2',
			type: 'path-across-oneturn-grey',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'water',
			target: 'system',
			type: 'path-green',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'file',
			type: 'path-vertical-twoturn-green',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'administration',
			type: 'path-vertical-twoturn-green',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'city',
			target: 'service',
			type: 'path-vertical-oneturn-green',
			sourceAnchor: 0,
			targetAnchor: 2,
		},
		// {
		// 	source: 'service',
		// 	target: 'administration',
		// 	type: 'path-green',
		// 	sourceAnchor: 0,
		// 	targetAnchor: 2,
		// },
		{
			source: 'system',
			target: 'point1',
			type: 'path-green',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'file',
			target: 'point1',
			type: 'path-vertical-oneturn-green',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'administration',
			target: 'point3',
			type: 'path-vertical-oneturn-green',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'service',
			target: 'point4',
			type: 'path-vertical-oneturn-green',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'point1',
			target: 'table_header',
			type: 'path-green',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'table_body4',
			target: 'date_factory',
			type: 'path-green',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'date_factory',
			target: 'date_maintain',
			type: 'path-green',
		},
		{
			source: 'date_maintain',
			target: 'date_quality',
			type: 'path-green',
		},
		{
			source: 'date_quality',
			target: 'date_assets',
			type: 'path-green',
		},
		{
			source: 'date_assets',
			target: 'date_service',
			type: 'path-green',
		},
		{
			source: 'date_service',
			target: 'city',
			type: 'path-green',
			sourceAnchor: 1,
			targetAnchor: 1,
		},
		{
			source: 'table_header',
			target: 'table_body1',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_header',
			target: 'table_body2',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_header',
			target: 'table_body3',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_header',
			target: 'table_body4',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body1',
			target: 'table_footer1',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body1',
			target: 'table_footer2',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body2',
			target: 'table_footer3',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body2',
			target: 'table_footer4',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body3',
			target: 'table_footer5',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body3',
			target: 'table_footer6',
			type: 'path-vertical-twoturn-green-small',
		},
		{
			source: 'table_body4',
			target: 'table_footer7',
			type: 'path-vertical-twoturn-green-small',
			sourceAnchor: 1,
		},
		{
			source: 'table_body4',
			target: 'table_footer8',
			type: 'path-vertical-twoturn-green-small',
			sourceAnchor: 1,
		},
		{
			source: 'water',
			target: 'pump',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'pump',
			target: 'waterworks',
			type: 'path-across-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'metering1',
			type: 'path-across-twoturn-animate',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'metering2',
			type: 'path-across-twoturn-animate',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'metering1',
			target: 'site1',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'site1',
			target: 'large_meter',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'large_meter',
			target: 'factory',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'factory',
			target: 'point2',
			type: 'path-across-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'metering2',
			target: 'site2',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'site2',
			target: 'meter',
			type: 'path-across-twoturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'meter',
			target: 'pool',
			type: 'path-across-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'pool',
			target: 'water_pump',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'building',
			type: 'path-animate',
			sourceAnchor: 3,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'building',
			type: 'path-vertical-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 1,
		},
		{
			source: 'building',
			target: 'point2',
			type: 'path-across-oneturn-animate',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'water',
			target: 'system',
			type: 'path-animate',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'waterworks',
			target: 'file',
			type: 'path-vertical-twoturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'water_pump',
			target: 'administration',
			type: 'path-vertical-twoturn-animate',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'city',
			target: 'service',
			type: 'path-vertical-oneturn-animate',
			sourceAnchor: 0,
			targetAnchor: 2,
		},
		{
			source: 'service',
			target: 'administration',
			type: 'path-animate',
			sourceAnchor: 0,
			targetAnchor: 2,
		},
		{
			source: 'system',
			target: 'point1',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'file',
			target: 'point1',
			type: 'path-vertical-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'administration',
			target: 'point3',
			type: 'path-vertical-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'service',
			target: 'point4',
			type: 'path-vertical-oneturn-animate',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'point1',
			target: 'table_header',
			type: 'path-animate',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'table_body4',
			target: 'date_factory',
			type: 'path-animate',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'date_factory',
			target: 'date_maintain',
			type: 'path-animate',
		},
		{
			source: 'date_maintain',
			target: 'date_quality',
			type: 'path-animate',
		},
		{
			source: 'date_quality',
			target: 'date_assets',
			type: 'path-animate',
		},
		{
			source: 'date_assets',
			target: 'date_service',
			type: 'path-animate',
		},
		{
			source: 'date_service',
			target: 'city',
			type: 'path-animate',
			sourceAnchor: 1,
			targetAnchor: 1,
		},
		{
			source: 'table_header',
			target: 'table_body1',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_header',
			target: 'table_body2',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_header',
			target: 'table_body3',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_header',
			target: 'table_body4',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body1',
			target: 'table_footer1',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body1',
			target: 'table_footer2',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body2',
			target: 'table_footer3',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body2',
			target: 'table_footer4',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body3',
			target: 'table_footer5',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body3',
			target: 'table_footer6',
			type: 'path-vertical-twoturn-animate-small',
		},
		{
			source: 'table_body4',
			target: 'table_footer7',
			type: 'path-vertical-twoturn-animate-small',
			sourceAnchor: 1,
		},
		{
			source: 'table_body4',
			target: 'table_footer8',
			type: 'path-vertical-twoturn-animate-small',
			sourceAnchor: 1,
		},
	],
};
