export const dataSource = {
	nodes: [
		{
			id: 'node1',
			x: 0,
			y: 0,
			// comboId: "combo1",
			type: 'dom-node',
			img: require('@/assets/overview/ic_data_model@2x.png'),
			label: '板块',
			description: '一级分类',
			style: {
				fill: '#F4F6F9', //填充色
				stroke: '#F4F6F9', //边框
			},
			textX: [],
			textY: [],
			// parentId: "combo1",
			url: 'path',
		},
		{
			id: 'node1_1',
			x: 787,
			y: 40,
			// comboId: "combo1",
			type: 'rect',
			label: '供电生态',
			size: [788, 36],
			anchorPoints: [[0.5, 1]],
			parentId: 'node1',
			url: 'path',
		},
		{
			id: 'node1_2',
			x: 473,
			y: 100,
			// comboId: "combo1",
			type: 'rect',
			label: 'XX',
			size: [160, 36],
			anchorPoints: [
				[0.5, 0],
				[1, 0.5],
				[0.5, 1],
			],
			parentId: 'node1',
			url: 'path',
		},
		{
			id: 'node1_3',
			x: 683,
			y: 100,
			// comboId: "combo1",
			type: 'rect',
			label: 'XX',
			size: [160, 36],
			anchorPoints: [
				[0.5, 0],
				[1, 0.5],
				[0, 0.5],
				[0.5, 1],
			],
			parentId: 'node1',
			url: 'path',
		},
		{
			id: 'node1_4',
			x: 893,
			y: 100,
			// comboId: "combo1",
			type: 'rect',
			label: 'XX',
			size: [160, 36],
			anchorPoints: [
				[0.5, 0],
				[1, 0.5],
				[0, 0.5],
				[0.5, 1],
			],
			parentId: 'node1',
			url: 'path',
		},
		{
			id: 'node1_5',
			x: 1101,
			y: 100,
			// comboId: "combo1",
			type: 'rect',
			label: 'XX',
			size: [160, 36],
			anchorPoints: [
				[0.5, 0],
				[0, 0.5],
				[0.5, 1],
			],
			parentId: 'node1',
			url: 'path',
		},
		{
			id: 'node2',
			x: 0,
			y: 155,
			// comboId: "combo2",
			type: 'dom-node',
			img: require('@/assets/overview/ic_data_business@2x.png'),
			label: 'XX域',
			size: [1251, 160],
			description: '二级分类',
			style: {
				fill: '#F4F6F9', //填充色
				stroke: '#F4F6F9', //边框
			},
			textX: [0, 172, 0],
			textY: [21, 101, 125],
			url: 'path',
		},
		{
			id: 'node2_1',
			x: 415,
			y: 234,

			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_2',
			x: 473,
			y: 234,
			// comboId: "combo2",
			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_3',
			x: 531,
			y: 234,
			// comboId: "combo2",
			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_4',
			x: 625,
			y: 234,
			// comboId: "combo2",
			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_5',
			x: 683,
			y: 234,
			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_6',
			x: 741,
			y: 234,
			type: 'rect',
			size: [44, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_7',
			x: 826,
			y: 234,
			type: 'rect',
			size: [26, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_8',
			x: 860,
			y: 234,
			type: 'rect',
			size: [26, 118],
			label: 'X\nX\nX\nX\nX',
			style: {
				fill: '#E4EAF2', //填充色
				stroke: '#E4EAF2', //边框
				radius: 4,
			},
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_9',
			x: 893,
			y: 234,
			type: 'rect',
			size: [26, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_10',
			x: 927,
			y: 234,
			type: 'rect',
			size: [26, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_11',
			x: 960,
			y: 234,
			type: 'rect',
			size: [26, 118],
			label: 'X\nX\nX\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_12',
			x: 1031.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_13',
			x: 1059.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_14',
			x: 1086.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_15',
			x: 1114.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_16',
			x: 1142.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node2_17',
			x: 1170.5,
			y: 234,
			type: 'rect',
			size: [21, 118],
			label: 'X\nX\nX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			parentId: 'node2',
			url: 'path',
		},
		{
			id: 'node3',
			x: 0,
			y: 331,
			type: 'dom-node',
			img: require('@/assets/overview/ic_data_theme@2x.png'),
			size: [1251, 140],
			label: 'XX主题',
			description: '一级分类',
			style: {
				fill: '#F4F6F9', //填充色
				stroke: '#F4F6F9', //边框
			},
			textX: [0, 165, 145],
			textY: [0, 94, 118],
			url: '/dataplan/businessTopic',
		},
		{
			id: 'node3_1',
			x: 473,
			y: 401,
			type: 'rect',
			size: [160, 56],
			label: 'XXXXXX',
			anchorPoints: [[0.5, 0]],
			parentId: 'node3',
			url: '/dataplan/businessTopic',
		},
		{
			id: 'node3_2',
			x: 775,
			y: 401,
			type: 'rect',
			size: [344, 56],
			label: 'XXXXXXXXXXX',
			anchorPoints: [[0.5, 0]],
			parentId: 'node3',
			url: '/dataplan/businessTopic',
		},
		{
			id: 'node3_3',
			x: 1101,
			y: 401,
			type: 'rect',
			size: [160, 56],
			label: 'XXXXXXXXXXX',
			anchorPoints: [[0.5, 0]],
			parentId: 'node3',
			url: '/dataplan/businessTopic',
		},
		{
			id: 'node4',
			x: 0,
			y: 487,
			type: 'dom-node',
			img: require('@/assets/overview/ic_data_source@2x.png'),
			size: [1251, 183],
			label: 'XXXXXXXXXXX',
			description: 'XXXXXXXXXXXXXXXXXXXXXX\n       XXXXXXXXXXX',
			style: {
				fill: '#F4F6F9', //填充色
				stroke: '#F4F6F9', //边框
			},
			textX: [0, 159, 120],
			textY: [20, 103, 140],
			url: 'path',
		},
		{
			id: 'node4_1',
			x: 393,
			y: 507,
			// comboId: "combo4",
			type: 'dom-node',
			size: [253, 143],
			label: 'XXXXXXXXXXX',
			description:
				'XXXXXXXXXXX\nXXXXXXXXXXX\nXXXXXXXXXXX，例如：\nXXXXXXXXXXX',
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 20, 20],
			textY: [0, 33, 127],
			parentId: 'node4',
			url: 'path',
		},
		{
			id: 'node4_2',
			x: 661,
			y: 507,
			type: 'dom-node',
			size: [253, 143],
			label: '大数据存储',
			description:
				'XXXXXXXXXXX，\nXXXXXXXXXXX，\nXXXXXXXXXXX种\nXXXXXXXXXXX',
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 20, 20],
			textY: [0, 33, 127],
			parentId: 'node4',
			url: 'path',
		},
		{
			id: 'node4_3',
			x: 928,
			y: 507,
			type: 'dom-node',
			size: [253, 143],
			label: 'NOSQL',
			description:
				'XXXXXXXXXXX、\nXXXXXXXXXXX\nXXXXXXXXXXX',
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 20, 20],
			textY: [0, 33, 104],
			parentId: 'node4',
			url: 'path',
		},
		{
			id: 'node5',
			x: 1267,
			y: 0,
			// comboId: "combo5",
			type: 'dom-node',
			size: [400, 671],
			img: require('@/assets/overview/ic_data_layer@2x.png'),
			label: 'XXXXXXXXXXX',
			description: 'XXXXXXXXXXX',
			textX: [167, 172, 130],
			textY: [36, 116, 140],
			style: {
				fill: '#F4F6F9',
				stroke: '#F4F6F9',
			},
			// parentId: "combo5",
			url: '/dataAssets/modelConfig',
		},
		{
			id: 'node5_1',
			x: 1291,
			y: 175,
			comboId: 'combo5',
			type: 'dom-node',
			size: [352, 106],
			label: 'ODS (Operational Data Store)',
			description: 'XXXXXXXXXXX\nXXXXXXXXXXX',
			anchorPoints: [[0.5, 1]],
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 21, 21],
			textY: [0, 33, 82],
			parentId: 'node5',
			url: '/dataAssets/modelConfig',
		},
		{
			id: 'node5_2',
			x: 1291,
			y: 297,
			comboId: 'combo5',
			type: 'dom-node',
			size: [352, 106],
			label: 'DWD (Data Warehouse Detail)',
			description: 'XXXXXXXXXXX，XXXXXXXXXXX，XXXXXXXXXXX\nXXXXXXXXXXX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
				[1, 0.5],
			],
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 21, 21],
			textY: [0, 33, 82],
			parentId: 'node5',
			url: '/dataAssets/modelConfig',
		},
		{
			id: 'node5_3',
			x: 1291,
			y: 419,
			comboId: 'combo5',
			type: 'dom-node',
			size: [352, 106],
			label: 'DWS (Data Warehouse Summary)',
			description:
				'XXXXXXXXXXX，XXXXXXXXXXX，XXXXXXXXXXX\nXXXXXXXXXXX',
			anchorPoints: [
				[0.5, 0],
				[0.5, 1],
			],
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 21, 21],
			textY: [0, 33, 80],
			parentId: 'node5',
			url: '/dataAssets/modelConfig',
		},
		{
			id: 'node5_4',
			x: 1291,
			y: 541,
			comboId: 'combo5',
			type: 'dom-node',
			size: [352, 106],
			label: 'ADS (Application Data Store)',
			description:
				'XXXXXXXXXXX\nXXXXXXXXXXX\nXXXXXXXXXXX',
			anchorPoints: [
				[0.5, 0],
				[1, 0.5],
			],
			labelCfg: {
				style: {
					fill: '#666666',
					fontFamily: 'PingFangSC-Medium',
					fontSize: 14,
					lineHeight: 22,
				},
			},
			textX: [0, 21, 21],
			textY: [0, 33, 98],
			parentId: 'node5',
			url: '/dataAssets/modelConfig',
		},
	],
	edges: [
		{
			source: 'node1_1',
			target: 'node1_2',
			sourceAnchor: 0,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 787, y: 70 },
				{ x: 473, y: 70 },
			],
		},
		{
			source: 'node1_1',
			target: 'node1_3',
			sourceAnchor: 0,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 787, y: 70 },
				{ x: 683, y: 70 },
			],
		},
		{
			source: 'node1_1',
			target: 'node1_4',
			sourceAnchor: 0,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 787, y: 70 },
				{ x: 893, y: 70 },
			],
		},
		{
			source: 'node1_1',
			target: 'node1_5',
			sourceAnchor: 0,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 787, y: 70 },
				{ x: 1101, y: 70 },
			],
		},
		{
			source: 'node1_2',
			target: 'node1_3',
			sourceAnchor: 1,
			targetAnchor: 2,
		},
		{
			source: 'node1_3',
			target: 'node1_4',
			sourceAnchor: 1,
			targetAnchor: 2,
		},
		{
			source: 'node1_4',
			target: 'node1_5',
			sourceAnchor: 1,
			targetAnchor: 1,
		},
		{
			source: 'node1_2',
			target: 'node2_1',
			sourceAnchor: 2,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 473, y: 146 },
				{ x: 415, y: 146 },
			],
		},
		{
			source: 'node1_2',
			target: 'node2_2',
			sourceAnchor: 2,
			targetAnchor: 0,
		},
		{
			source: 'node1_2',
			target: 'node2_3',
			sourceAnchor: 2,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 473, y: 146 },
				{ x: 531, y: 146 },
			],
		},
		{
			source: 'node1_3',
			target: 'node2_4',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 683, y: 146 },
				{ x: 625, y: 146 },
			],
		},
		{
			source: 'node1_3',
			target: 'node2_5',
			sourceAnchor: 3,
			targetAnchor: 0,
		},
		{
			source: 'node1_3',
			target: 'node2_6',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 683, y: 146 },
				{ x: 741, y: 146 },
			],
		},
		{
			source: 'node1_4',
			target: 'node2_7',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 893, y: 146 },
				{ x: 826, y: 146 },
			],
		},
		{
			source: 'node1_4',
			target: 'node2_8',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 893, y: 146 },
				{ x: 860, y: 146 },
			],
		},
		{
			source: 'node1_4',
			target: 'node2_9',
			sourceAnchor: 3,
			targetAnchor: 0,
		},
		{
			source: 'node1_4',
			target: 'node2_10',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 893, y: 146 },
				{ x: 927, y: 146 },
			],
		},
		{
			source: 'node1_4',
			target: 'node2_11',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 893, y: 146 },
				{ x: 960, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_12',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1031.5, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_13',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1059.5, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_14',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1086.5, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_15',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1114.5, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_16',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1142.5, y: 146 },
			],
		},
		{
			source: 'node1_5',
			target: 'node2_17',
			sourceAnchor: 3,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1101, y: 146 },
				{ x: 1170.5, y: 146 },
			],
		},
		{
			source: 'node2_1',
			target: 'node3_1',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 415, y: 323 },
				{ x: 473, y: 323 },
			],
		},
		{
			source: 'node2_2',
			target: 'node3_1',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'node2_3',
			target: 'node3_1',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 531, y: 323 },
				{ x: 473, y: 323 },
			],
		},
		{
			source: 'node2_4',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 625, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_5',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 683, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_6',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 741, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_7',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 826, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_8',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 860, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_9',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 893, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_10',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 927, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_11',
			target: 'node3_2',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 960, y: 323 },
				{ x: 775, y: 323 },
			],
		},
		{
			source: 'node2_12',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1031.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node2_13',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1059.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node2_14',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1086.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node2_15',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1114.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node2_16',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1142.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node2_17',
			target: 'node3_3',
			sourceAnchor: 1,
			targetAnchor: 0,
			type: 'polyline',
			controlPoints: [
				{ x: 1170.5, y: 323 },
				{ x: 1101, y: 323 },
			],
		},
		{
			source: 'node5_1',
			target: 'node5_2',
			sourceAnchor: 0,
			targetAnchor: 0,
		},
		{
			source: 'node5_2',
			target: 'node5_3',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'node5_3',
			target: 'node5_4',
			sourceAnchor: 1,
			targetAnchor: 0,
		},
		{
			source: 'node5_2',
			target: 'node5_4',
			sourceAnchor: 2,
			targetAnchor: 1,
			type: 'polyline',
			controlPoints: [
				{ x: 1655, y: 353 },
				{ x: 1655, y: 597 },
			],
		},
	],
};
